In [2]:
import pandas as pd
import re
import nltk

In [3]:
# English Dataset
df_eng = pd.read_csv("../data/raw/spam.csv", encoding="latin-1")
df_eng = df_eng[['v1', 'v2']]
df_eng.columns = ['label', 'message']

# Hindi Dataset
df_hindi = pd.read_csv("../data/raw/hindi_spam.csv")
df_hindi = df_hindi[df_hindi["lang"].isin(["english", "hindi"])]
df_hindi = df_hindi[["labels", "text"]]
df_hindi.columns = ["label", "message"]

# Marathi Dataset
df_marathi = pd.read_csv("../data/raw/marathi_spam.csv")

In [4]:
print(df_eng.shape)
print(df_hindi.shape)
print(df_marathi.shape)

(5572, 2)
(11143, 2)
(250, 2)


In [5]:
df_eng

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will Ì_ b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [6]:
df_marathi

,label,message
0,spam,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...
1,spam,तुमचे KYC अपडेट करा नाहीतर खाते बंद होईल. संदर...
2,spam,तुमचे UPI खाते verify करा. संदर्भ क्र.: 1002
3,spam,QR Code स्कॅन करून बक्षीस मिळवा. संदर्भ क्र.: ...
4,spam,तुमच्या खात्यात ₹75000 जमा करण्यासाठी OTP टाका...
...,...,...
245,ham,उद्या कॉलेजला येणार का? (संदेश 121)
246,ham,मी ५ वाजता घरी येतो. (संदेश 122)
247,ham,आजचा क्लास किती वाजता आहे? (संदेश 123)
248,ham,तुझा प्रोजेक्ट पूर्ण झाला का? (संदेश 124)


In [7]:
df_hindi

,label,message
0,spam,No 1 POLYPHONIC tone 4 ur mob every week! Just...
2,ham,हाय यह अच्छी तरह से जाने के लिए मेरा शुक्रिया!
5,ham,"मैं तुम्हें बाद में फोन करता हूँ, नेटवर्क नहीं..."
8,ham,भारत ले जाना है:)
9,spam,CURGERAN! आपके मोबाइल नंबर को 5 पाउंड इनाम GUR...
...,...,...
22271,spam,Win the newest “Harry Potter and the Order of ...
22272,ham,We have all rounder:)so not required:)
22275,ham,आप दूर दूर निगम में मिलते हैं... आप देख सकते ह...
22276,ham,आप कैसे कर रहे हैं?


In [8]:
df = pd.concat([df_eng,df_hindi,df_marathi],ignore_index= True)

In [9]:
df.shape

(16965, 2)

In [10]:
df.head

<bound method NDFrame.head of       label                                            message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
16960   ham                उद्या कॉलेजला येणार का? (संदेश 121)
16961   ham                   मी ५ वाजता घरी येतो. (संदेश 122)
16962   ham             आजचा क्लास किती वाजता आहे? (संदेश 123)
16963   ham          तुझा प्रोजेक्ट पूर्ण झाला का? (संदेश 124)
16964   ham             चल संध्याकाळी फिरायला जाऊ. (संदेश 125)

[16965 rows x 2 columns]>

In [11]:
df.tail

<bound method NDFrame.tail of       label                                            message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
16960   ham                उद्या कॉलेजला येणार का? (संदेश 121)
16961   ham                   मी ५ वाजता घरी येतो. (संदेश 122)
16962   ham             आजचा क्लास किती वाजता आहे? (संदेश 123)
16963   ham          तुझा प्रोजेक्ट पूर्ण झाला का? (संदेश 124)
16964   ham             चल संध्याकाळी फिरायला जाऊ. (संदेश 125)

[16965 rows x 2 columns]>

In [12]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(5718)

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16965 entries, 0 to 16964
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    16965 non-null  str  
 1   message  16965 non-null  str  
dtypes: str(2)
memory usage: 2.1 MB


In [15]:
df = df.drop_duplicates()

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
print(df.shape)

(11247, 2)


In [18]:
df['label']=df['label'].map({
    "ham":0,
    "spam":1
})

In [19]:
df["label"].value_counts()

label
0    9603
1    1644
Name: count, dtype: int64

In [20]:
import nltk

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


False

In [21]:
import string
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [22]:
from nltk.tokenize import word_tokenize
def transform_text(text):
    text = text.lower()
    #to convert text into lower case
    

    text = word_tokenize(text)

    return text

In [39]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Prime\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Prime\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


True

In [23]:
transform_text("Hello Jyoti! Welcome To Machine Learning.")

['hello', 'jyoti', '!', 'welcome', 'to', 'machine', 'learning', '.']

In [50]:
def transform_text(text):

    import re

    # English असेल तर preprocessing
    if re.search(r'[a-zA-Z]', text):

        text = text.lower()
        text = nltk.word_tokenize(text)

        y = []

        for i in text:
            if i not in string.punctuation:
                y.append(i)

        z = []

        for i in y:
            if i not in stopwords.words("english"):
                z.append(ps.stem(i))

        return " ".join(z)

    # Hindi / Marathi
    else:
        return text.strip()

In [51]:
transform_text("Hello Jyoti! Welcome To Machine Learning.")

'hello jyoti welcom machin learn'

In [52]:
transform_text("Hello Jyoti! How are you doing today?")

'hello jyoti today'

In [53]:
df["transformed_message"] = df["message"].apply(transform_text)

In [54]:
df.head()






,label,message,transformed_message
0,0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi .. avail bugi n great wo...
1,0,Ok lar... Joking wif u oni...,ok lar ... joke wif u oni ...
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entri 2 wkli comp win fa cup final tkt 21...
3,0,U dun say so early hor... U c already then say...,u dun say earli hor ... u c alreadi say ...
4,0,"Nah I don't think he goes to usf, he lives aro...",nah n't think goe usf live around though


In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=3000)

In [56]:
X = tfidf.fit_transform(df["transformed_message"]).toarray()

y = df["label"]

In [57]:
X.shape

(11247, 3000)

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [60]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (8997, 3000)
X_test : (2250, 3000)
y_train: (8997,)
y_test : (2250,)


In [61]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score

In [62]:
mnb = MultinomialNB()

In [63]:
mnb.fit(X_train, y_train)


,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)Number of samples encountered for each class during fitting. Thisvalue is weighted by the sample weight when provided.","ndarray[float64](2,)","[7691.,1306.]"
"class_log_prior_ class_log_prior_: ndarray of shape (n_classes,)Smoothed empirical log probability for each class.","ndarray[float64](2,)","[-0.16,-1.93]"
"classes_ classes_: ndarray of shape (n_classes,)Class labels known to the classifier","ndarray[int64](2,)","[0,1]"
"feature_count_ feature_count_: ndarray of shape (n_classes, n_features)Number of samples encountered for each (class, feature)during fitting. This value is weighted by the sample weight whenprovided.","ndarray[float64](2, 3000)","[[ 0. , 0.34, 0. ,..., 0. , 0. , 0.75], [ 4.62,12.95, 0.82,..., 0.82, 1.38, 1.41]]"
"feature_log_prob_ feature_log_prob_: ndarray of shape (n_classes, n_features)Empirical log probability of featuresgiven a class, ``P(x_i|y)``.","ndarray[float64](2, 3000)","[[-9.91,-9.62,-9.91,...,-9.91,-9.91,-9.35], [-7.14,-6.23,-8.27,...,-8.27,-8. ,-7.99]]"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,3000


In [64]:
y_pred = mnb.predict(X_test)

In [65]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy : 0.9511111111111111
Precision: 0.9913793103448276
[[1910    2]
 [ 108  230]]


In [66]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred_lr))
print("Precision:", precision_score(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))

Accuracy : 0.9502222222222222
Precision: 0.9956140350877193
[[1911    1]
 [ 111  227]]


In [67]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)
y_pred_lr = lr.predict(X_test)

print("Accuracy:",accuracy_score(y_test,y_pred_lr))
print("Precision:",precision_score(y_test,y_pred_lr))
print(confusion_matrix(y_test,y_pred_lr))

Accuracy: 0.9502222222222222
Precision: 0.9956140350877193
[[1911    1]
 [ 111  227]]


In [68]:
from sklearn.svm import SVC
svm = SVC(kernel='linear')
svm.fit(X_train,y_train)

y_pred_svm = svm.predict(X_test)

print("Accuracy:",accuracy_score(y_test,y_pred_svm))
print("Precision:",precision_score(y_test,y_pred_svm))
print(confusion_matrix(y_test,y_pred_svm))


Accuracy: 0.9644444444444444
Precision: 0.9813432835820896
[[1907    5]
 [  75  263]]


In [69]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42)

rf.fit(X_train,y_train)

y_pred_rf = rf.predict(X_test)

print("Accuracy:",accuracy_score(y_test,y_pred_rf))
print("Precision:",precision_score(y_test,y_pred_rf))
print(confusion_matrix(y_test,y_pred_rf))

Accuracy: 0.9613333333333334
Precision: 0.9771863117870723
[[1906    6]
 [  81  257]]


In [70]:
import pickle

In [71]:
pickle.dump(tfidf,open("../models/vectorizer.pkl","wb"))
pickle.dump(svm,open("../models/model.pkl","wb"))

In [72]:
df[df["message"].str.contains("जीत गए हैं", na=False)]

,label,message,transformed_message
15599,1,"आप जीत गए हैं? 2,000 डॉलर या एक पुरस्कार! दावा...","आप जीत गए हैं 2,000 डॉलर या एक पुरस्कार दावा क..."


In [73]:
df[df["message"].str.contains("अभिनंदन", na=False)]

,label,message,transformed_message
16715,1,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...
16725,1,अभिनंदन! तुम्ही ₹75000 जिंकले आहेत. लगेच लिंकव...,अभिनंदन! तुम्ही ₹75000 जिंकले आहेत. लगेच लिंकव...
16735,1,अभिनंदन! तुम्ही ₹25000 जिंकले आहेत. लगेच लिंकव...,अभिनंदन! तुम्ही ₹25000 जिंकले आहेत. लगेच लिंकव...
16745,1,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...
16755,1,अभिनंदन! तुम्ही ₹75000 जिंकले आहेत. लगेच लिंकव...,अभिनंदन! तुम्ही ₹75000 जिंकले आहेत. लगेच लिंकव...
16765,1,अभिनंदन! तुम्ही ₹25000 जिंकले आहेत. लगेच लिंकव...,अभिनंदन! तुम्ही ₹25000 जिंकले आहेत. लगेच लिंकव...
16775,1,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...
16785,1,अभिनंदन! तुम्ही ₹75000 जिंकले आहेत. लगेच लिंकव...,अभिनंदन! तुम्ही ₹75000 जिंकले आहेत. लगेच लिंकव...
16795,1,अभिनंदन! तुम्ही ₹25000 जिंकले आहेत. लगेच लिंकव...,अभिनंदन! तुम्ही ₹25000 जिंकले आहेत. लगेच लिंकव...
16805,1,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...


In [74]:
df[df["message"].str.contains("जिंकले", na=False)]

,label,message,transformed_message
16715,1,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...
16725,1,अभिनंदन! तुम्ही ₹75000 जिंकले आहेत. लगेच लिंकव...,अभिनंदन! तुम्ही ₹75000 जिंकले आहेत. लगेच लिंकव...
16735,1,अभिनंदन! तुम्ही ₹25000 जिंकले आहेत. लगेच लिंकव...,अभिनंदन! तुम्ही ₹25000 जिंकले आहेत. लगेच लिंकव...
16745,1,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...
16755,1,अभिनंदन! तुम्ही ₹75000 जिंकले आहेत. लगेच लिंकव...,अभिनंदन! तुम्ही ₹75000 जिंकले आहेत. लगेच लिंकव...
16765,1,अभिनंदन! तुम्ही ₹25000 जिंकले आहेत. लगेच लिंकव...,अभिनंदन! तुम्ही ₹25000 जिंकले आहेत. लगेच लिंकव...
16775,1,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...
16785,1,अभिनंदन! तुम्ही ₹75000 जिंकले आहेत. लगेच लिंकव...,अभिनंदन! तुम्ही ₹75000 जिंकले आहेत. लगेच लिंकव...
16795,1,अभिनंदन! तुम्ही ₹25000 जिंकले आहेत. लगेच लिंकव...,अभिनंदन! तुम्ही ₹25000 जिंकले आहेत. लगेच लिंकव...
16805,1,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...,अभिनंदन! तुम्ही ₹5000 जिंकले आहेत. लगेच लिंकवर...


In [75]:
df[df["message"].str.contains("लिंक", na=False)]

,label,message,transformed_message
7580,0,अब कि आप बंद करना शुरू कर दिया है. बस अधिक अच्...,अब कि आप बंद करना शुरू कर दिया है. बस अधिक अच्...
9328,0,Yanny मैं शहर लिंक में चल रहा हूँ अब तेजी से न...,yanni मैं शहर लिंक में चल रहा हूँ अब तेजी से न...
11834,1,"256XMIGCALLLL: आपका क्रेडिट उपयोग करने के लिए,...",256xmigcalll आपका क्रेडिट उपयोग करने के लिए अग...
12745,1,आपकी तस्वीर के लिए एक लिंक भेजा गया है. आप भी ...,आपकी तस्वीर के लिए एक लिंक भेजा गया है आप भी h...
13192,1,MMob> लिंक एक प्रीमियम पिपर खेल प्राप्त करने क...,mmob लिंक एक प्रीमियम पिपर खेल प्राप्त करने के...
14189,0,ओला आज शायद आप के लिए वापस मिल जाएगा लेकिन मैं...,ओला आज शायद आप के लिए वापस मिल जाएगा लेकिन मैं...
14822,1,वोट के लिए धन्यवाद. अब अपने मोबाइल पर कर्क के ...,वोट के लिए धन्यवाद अब अपने मोबाइल पर कर्क के स...
14842,0,"आह, देख, तुझे लिंको में होना है; मैं तुझे पृथ्...","आह, देख, तुझे लिंको में होना है; मैं तुझे पृथ्..."
14931,1,प्रिय Varger अपना अगला भोजन हम पर है. अपने pc ...,प्रिय varger अपना अगला भोजन हम पर है अपने pc 2...
15716,1,MMoo यो यो यो यो-यहाँ हमारे सदस्यों के लिए गर्...,mmoo यो यो यो यो-यहाँ हमारे सदस्यों के लिए गर्...
